### ISSUE TITLE
깃헙 접속하면 좌측에 항상 뜨는데 삭제할 방법이 없나요?

### ISSUE THREAD

**Issue by lvmedh83** [mcocl/awesome-pr-whoami#54]
안녕하세요.
강좌 잘봤습니다.
실습하다가 어떻게 된지는 모르겠는데
깃헙 접속하면 좌측에 mcocl/awesome-pr-whoami 가 표기 되는데
안보이게 하는 방법은 없을까요?

**Comment by junngo** [comment]
@lvmedh83 님 안녕하세요 :)
해당 레파지토리는 PR만 확인을 하다가 답변이 늦어져서 죄송합니다😢
좌측에 표시되는 리스트는 지금 까지 참여했던 레파지토리가 노출이 되어, 보이지 않게 조정할 수가 없을 것으로 판단이 돼요.
제 경우에는 좌측 표시되는 레파짓이 외부에 노출이 되는 것도 아니고 , 레파지토리가 많아서 크게 신경을 쓰지 않고 있습니다 😢😢
이에 대해서 참고 부탁드리겠습니다.
